name: Flow-CI-Honkit

on:
  push:
    branches:
        - main # pls change trigger on each repos
env:
  USER_EMAIL: warfejm@nih.gov
  USER_NAME: jmwarfe
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  Build-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Build and deploy
        uses: monstar-lab-oss/honkit-ghpages-action@main
        
        
  
